### ISSUE TITLE
Issue while training 

### ISSUE THREAD

**Issue by gauridhawan** [Tacode/PSPNet_VOC#3]
Hi, I tried running the train function and came across this error

```Traceback (most recent call last):
  File "train.py", line 150, in <module>
    train()
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 114, in train
    for i,(x, y, y_cls) in enumerate(train_loader):
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/gd1302/miniconda3/envs/cv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/gd1302/pspnet/PSPNet_VOC/voc_loader.py", line 101, in __getitem__
    cls = self.getcls(lbl)
  File "/scratch/gd1302/pspnet/PSPNet_VOC/voc_loader.py", line 108, in getcls
    cls = np.zeros((21),dtype=int)
IndexError: index 21 is out of bounds for axis 0 with size 21
```

Do you know what could be causing this?

**Comment by Ivanyan0516** [comment]
I meet the same question,have you solved this?

**Comment by mesakh123** [comment]
I have also the same problem, I found out that some of the segmentation masks have more than 21 classes (20 classes + 1 background) after encoding process. I solve it with changing the transform function on the voc_loader.py by ignoring classes more than the number of n_classes :
```
def transform(self, img, lbl):
        if self.img_size == ('same', 'same'):
            pass
        else:
            img = img.resize((self.img_size[0], self.img_size[1]))  # uint8 with RGB mode
            lbl = lbl.resize((self.img_size[0], self.img_size[1]))
        img = self.tf(img)
        lbl = torch.from_numpy(np.array(lbl)).long()
        lbl[lbl == 255] = 0
        lbl[lbl>=self.n_classes]=0 #new code here

        return img, lbl
```
